---
#permalink: pretty
encoding: UTF-8
markdown: redcarpet
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
name: Chasing the Whale
url: http://www.chasingthewhale.cc
sass:
  sass_dir: _scss
  style: :compressed
copyright: "Erik Svedäng and Andreas Zecher"
author: "Erik Svedäng and Andreas Zecher"
language: "en-GB"
subtitle: "A slow talk show about independent games and related topics."
description: "Chasing the Whale is a weekly podcast about independent games and related topics by Erik Svedäng and Andreas Zecher. New episode every Tuesday."
email: "podcast@chasingthewhale.cc"
cover: "http://www.chasingthewhale.cc/img/cover.png"
category: "Games &amp; Hobbies"
subcategory: "Video Games"
---